services:
  - type: web
    name: flask-playwright
    env: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      python -m playwright install chromium
      gunicorn app:app --timeout 120